title: Shamim Ahmed
Logo: sam.jpg
description: "RESEARCH PROFILE


Mr. Shamim Ahmed
Professor (Assistant)
Department of Computer Science and Engineering (CSE)
Bangladesh University of Business and Technology
Dhaka-1216, Bangladesh.


Mobile	+8801672917779
Email	shamim.6feb@gmail.com 
shamim.a@bubt.edu.bd

Web	https://cse.bubt.edu.bd/facultydetails/22/

ORCID	0000-0002-9968-4128
Google Scholar	https://scholar.google.com/citations?user=PMfknEIAAAAJ&hl=en

ResearchGate	https://www.researchgate.net/profile/Shamim-Ahmed-38/research

Web of Science	https://www.webofscience.com/wos/author/record/AGR-5672-2022


"
theme: jekyll-theme-minimal

